apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
spec:
  type: NodePort
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 5000        # Service internal port
      targetPort: 5000  # Container target port
      nodePort: 30007   # Publicly accessible node port